#!/usr/bin/env node
// Pins Apple's App Store Connect OpenAPI spec and regenerates src/generated/asc-api.ts from it.
//
//   npm run spec:update     download the latest spec from Apple, pin it, regenerate types
//   npm run spec:generate   regenerate types from the pinned spec (offline)
//
// The pinned spec lives in spec/openapi.oas.json.gz. spec/VERSION.json records its version and
// SHA-256, so a review of a spec bump shows exactly what changed. Only the schemas listed in
// scripts/spec-schemas.json (and what they reference) are generated, which keeps the types small.

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { gunzipSync, gzipSync } from "node:zlib";
import openapiTS, { astToString } from "openapi-typescript";

const SPEC_URL =
  "https://developer.apple.com/sample-code/app-store-connect/app-store-connect-openapi-specification.zip";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pinnedPath = join(root, "spec/openapi.oas.json.gz");
const versionPath = join(root, "spec/VERSION.json");
const outPath = join(root, "src/generated/asc-api.ts");
const offline = process.argv.includes("--offline");

let specText;
if (offline) {
  specText = gunzipSync(readFileSync(pinnedPath)).toString("utf8");
  const pinned = JSON.parse(readFileSync(versionPath, "utf8"));
  const sha = sha256(specText);
  if (sha !== pinned.sha256) {
    throw new Error(`spec/openapi.oas.json.gz does not match spec/VERSION.json (${sha} != ${pinned.sha256})`);
  }
} else {
  const dir = mkdtempSync(join(tmpdir(), "asc-spec-"));
  try {
    const res = await fetch(SPEC_URL);
    if (!res.ok) throw new Error(`Download failed: HTTP ${res.status} ${SPEC_URL}`);
    const zipPath = join(dir, "spec.zip");
    writeFileSync(zipPath, Buffer.from(await res.arrayBuffer()));
    specText = execFileSync("unzip", ["-p", zipPath, "openapi.oas.json"], { maxBuffer: 256 * 1024 * 1024 }).toString("utf8");
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
  writeFileSync(pinnedPath, gzipSync(specText, { level: 9 }));
}

const spec = JSON.parse(specText);
const version = spec.info?.version;
const sha = sha256(specText);
writeFileSync(versionPath, JSON.stringify({ version, sha256: sha, source: SPEC_URL }, null, 2) + "\n");

// Keep the root schemas and everything they reference.
const { roots } = JSON.parse(readFileSync(join(root, "scripts/spec-schemas.json"), "utf8"));
const all = spec.components.schemas;
const keep = new Set();
const queue = [...roots];
while (queue.length) {
  const name = queue.pop();
  if (keep.has(name)) continue;
  if (!all[name]) throw new Error(`Schema ${name} is not in spec ${version}`);
  keep.add(name);
  JSON.stringify(all[name], (key, value) => {
    if (key === "$ref" && typeof value === "string") queue.push(value.split("/").pop());
    return value;
  });
}
const schemas = Object.fromEntries([...keep].sort().map((name) => [name, all[name]]));
const pruned = { openapi: spec.openapi, info: spec.info, paths: {}, components: { schemas } };

const ast = await openapiTS(pruned, { alphabetize: true });
const header = `// Generated by scripts/update-spec.mjs from App Store Connect API ${version}. Do not edit.\n// Spec SHA-256: ${sha}\n\n`;
writeFileSync(outPath, header + astToString(ast));
console.log(`App Store Connect API ${version}: ${keep.size} schemas -> ${outPath}`);

function sha256(text) {
  return createHash("sha256").update(text).digest("hex");
}
